time_tracking/urls.py
"""
time_tracking provides time tracking capabilities to be used in the
django framework.
Copyright (C) 2013 Robert Robinson rerobins@meerkatlabs.org

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from time_tracking.views.project import ProjectCreateView, ProjectDetailView
from time_tracking.views.project import ProjectEditView, ProjectDeleteView
from time_tracking.views.project import ProjectListView, ProjectCopyView
from time_tracking.views.category import CategoryCreateView, CategoryDetailView
from time_tracking.views.category import CategoryEditView, CategoryDeleteView
from time_tracking.views.record import RecordCreateView, RecordDeleteView
from time_tracking.views.record import RecordCloseView, RecordEditView
from time_tracking.views.location import LocationCreateView, LocationDetailView
from time_tracking.views.location import LocationEditView, LocationDeleteView
from time_tracking.views.location import LocationListView

urlpatterns = patterns('',

    ## House keeping
    url(r'^license/',
        TemplateView.as_view(template_name="time_tracking/license.html")),

    ## Project manipulation
    url(r'^$', login_required(ProjectListView.as_view()),
        name='project_list_view'),
    url(r'^add/project/$', login_required(
        ProjectCreateView.as_view()),
            name='project_create_view'),
    url(r'^project/(?P<project_slug>[^/]+)/$', login_required(
        ProjectDetailView.as_view()),
        name='project_detail_view'),
    url(r'^edit/project/(?P<project_slug>[^/]+)/$', login_required(
        ProjectEditView.as_view()),
        name='project_edit_view'),
    url(r'^delete/project/(?P<project_slug>[^/]+)/$', login_required(
        ProjectDeleteView.as_view()),
        name='project_delete_view'),
    url(r'^copy/project/(?P<project_slug>[^/]+)/$', login_required(
        ProjectCopyView.as_view()),
        name='project_copy_view'),

    ## Record manipulation
    url(r'^project/(?P<project_slug>[^/]+)/add/$',
        login_required(RecordCreateView.as_view()),
        name='record_create_view'),
    url(r'^project/(?P<project_slug>[^/]+)/delete/(?P<pk>\d+)/$',
        login_required(RecordDeleteView.as_view()),
        name='record_delete_view'),
    url(r'^project/(?P<project_slug>[^/]+)/close/(?P<pk>\d+)/$',
        login_required(RecordCloseView.as_view()),
        name='record_close_view'),
    url(r'^project/(?P<project_slug>[^/]+)/edit/(?P<pk>\d+)/$',
        login_required(RecordEditView.as_view()),
        name='record_edit_view'),

    ## Category manipulation
    url(r'^add/project/(?P<project_slug>[^/]+)/category/$', login_required(
        CategoryCreateView.as_view()),
            name='category_create_view'),
    url(r'^project/(?P<project_slug>[^/]+)/category/'
        + '(?P<category_slug>[^/]+)/$', login_required(
        CategoryDetailView.as_view()),
        name='category_detail_view'),
    url(r'^edit/project/(?P<project_slug>[^/]+)/category/'
        + '(?P<category_slug>[^/]+)/$', login_required(
        CategoryEditView.as_view()),
        name='category_edit_view'),
    url(r'^delete/project/(?P<project_slug>[^/]+)/category/'
        + '(?P<category_slug>[^/]+)/$', login_required(
        CategoryDeleteView.as_view()),
        name='category_delete_view'),

    ## Location manipulation
    url(r'^project/(?P<project_slug>[^/]+)/locations/$', login_required(LocationListView.as_view()),
        name='location_list_view'),
    url(r'^add/project/(?P<project_slug>[^/]+)/location/$', login_required(
        LocationCreateView.as_view()),
            name='location_create_view'),
    url(r'^project/(?P<project_slug>[^/]+)/location/(?P<location_slug>[^/]+)/$', login_required(
        LocationDetailView.as_view()),
        name='location_detail_view'),
    url(r'^edit/project/(?P<project_slug>[^/]+)/location/(?P<location_slug>[^/]+)/$', login_required(
        LocationEditView.as_view()),
        name='location_edit_view'),
    url(r'^delete/project/(?P<project_slug>[^/]+)/location/(?P<location_slug>[^/]+)/$', login_required(
        LocationDeleteView.as_view()),
        name='location_delete_view'),

    ## Reports per Project


)

time_tracking/models.py
"""
time_tracking provides time tracking capabilities to be used in the
django framework.
Copyright (C) 2013 Robert Robinson rerobins@meerkatlabs.org

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils import timezone
import pytz


class Project(models.Model):
    """
        Basic Project object that will group a selection of time records
        together.
    """
    owner = models.ForeignKey(User)
    name = models.CharField(max_length=50)
    slug = models.SlugField(editable=False)
    template = models.BooleanField(default=False)
    description = models.TextField(blank=True, default="")

    class Meta:
        unique_together = (('slug', 'owner'),)
        ordering = ['name']

    def get_absolute_url(self):
        """
            Return the URL for the project.
        """
        return reverse('project_detail_view',
            kwargs={'project_slug': self.slug})

    def get_edit_url(self):
        """
            Return URL for editing a project.
        """
        return reverse('project_edit_view',
            kwargs={'project_slug': self.slug})

    def get_delete_url(self):
        """
            Return URL for deleting a project.
        """
        return reverse('project_delete_view',
            kwargs={'project_slug': self.slug})

    def get_add_category_url(self):
        """
            Return URL for adding a category to this project.
        """
        return reverse('category_create_view',
            kwargs={'project_slug': self.slug})
        
    def get_add_location_url(self):
        """
            Return URL for adding a locations to this project.
        """
        return reverse('location_create_view',
            kwargs={'project_slug': self.slug})

    def get_copy_project_url(self):
        """
            Return URL for copying the project to a new value.
        """
        return reverse('project_copy_view',
            kwargs={'project_slug': self.slug})

    def get_add_record_url(self):
        """
            Return the URL for creating a new record object.
        """
        return reverse('record_create_view',
            kwargs={'project_slug': self.slug})

    def __unicode__(self):
        """
            Human readable strin representing the project.
        """
        return self.name


class Category(models.Model):
    """
        Category that will allow for the type of work to be documented.
    """
    project = models.ForeignKey(Project)
    name = models.CharField(max_length=50)
    slug = models.SlugField(editable=False)
    description = models.TextField(blank=True, default="")

    class Meta:
        unique_together = (('slug', 'project'),)
        ordering = ['name']

    def get_absolute_url(self):
        """
            Return the aboslute url that is used to view the details of this
            object.
        """
        return reverse('category_detail_view',
            kwargs={'project_slug': self.project.slug,
                    'category_slug': self.slug})

    def get_edit_url(self):
        """
            Return the url that will be used to edit this object.
        """
        return reverse('category_edit_view',
            kwargs={'project_slug': self.project.slug,
                    'category_slug': self.slug})

    def get_delete_url(self):
        """
            Return the url that will be used to delete this object.
        """
        return reverse('category_delete_view',
            kwargs={'project_slug': self.project.slug,
                    'category_slug': self.slug})

    def __unicode__(self):
        """
            Human readable version of this object.
        """
        return self.name


class Location(models.Model):
    """
        Location that can be applied to records to show that the time was spent
        in a specific location.
    """
    project = models.ForeignKey(Project)
    name = models.CharField(max_length=50)
    slug = models.SlugField(editable=False)
    address = models.CharField(max_length=255, blank=True, default="")
    description = models.TextField(blank=True, default="")

    class Meta:
        unique_together = (('project', 'slug'),)
        ordering = ['name']

    def get_absolute_url(self):
        """
            Return the absolute url for the detail view of this object.
        """
        return reverse('location_detail_view',
            kwargs={'project_slug': self.project.slug,
                    'location_slug': self.slug})

    def get_edit_url(self):
        """
            Return the absolute url for the editing of this object.
        """
        return reverse('location_edit_view',
            kwargs={'project_slug': self.project.slug,
                    'location_slug': self.slug})

    def get_delete_url(self):
        """
            Return the absolute url for the deleting of this object.
        """
        return reverse('location_delete_view',
            kwargs={'project_slug': self.project.slug,
                    'location_slug': self.slug})

    def __unicode__(self):
        return self.name

# Time zone choices for all of the record date time values.
timezone_choices = [(time_zone, time_zone)
    for time_zone in pytz.common_timezones]


class Record(models.Model):
    """
        Model object that will contain information about the start times of
        work on a project and the duration of the amount of time that the
        project was worked on.
    """
    project = models.ForeignKey(Project)
    brief_description = models.CharField(max_length=255, blank=True)
    start_time = models.DateTimeField()
    start_time_tz = models.CharField(max_length=50, choices=timezone_choices)
    end_time = models.DateTimeField(null=True, blank=True)
    end_time_tz = models.CharField(max_length=50, choices=timezone_choices,
        blank=True)
    category = models.ForeignKey(Category, null=True, blank=True,
                on_delete=models.SET_NULL)
    location = models.ForeignKey(Location, blank=True, null=True,
                on_delete=models.SET_NULL)
    description = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['start_time', 'end_time']

    def close(self):
        """
            Close the record as a completed activity, but only if the record
            doesn't already have an end time defined.
        """
        if self.end_time is None:
            self.end_time = timezone.now()
            self.end_time_tz = timezone.get_current_timezone()

            if self.end_time >= self.start_time:
                self.save()

    def duration(self):
        """
            Determine the amount of time that has occurred in this record value
            in seconds
        """
        if self.end_time is None:
            return 0
        else:
            duration = self.end_time - self.start_time
            return duration.seconds + duration.microseconds / 1E6

    def get_edit_url(self):
        """
            Return URL for editing a record.
        """
        return reverse('record_edit_view',
            kwargs={'project_slug': self.project.slug,
                    'pk': self.pk})

    def get_delete_url(self):
        """
            Return URL for deleting a record.
        """
        return reverse('record_delete_view',
            kwargs={'project_slug': self.project.slug,
                    'pk': self.pk})

    def get_close_url(self):
        """
            Return URL for closing a record.
        """
        return reverse('record_close_view',
            kwargs={'project_slug': self.project.slug,
                    'pk': self.pk})


def convert_time(time_value, timezone_value):
    """
        Converts the time value into the time zone value provided.
    """
    time = timezone.make_naive(time_value, timezone.get_current_timezone())
    time = timezone.make_aware(time, timezone_value)
    return time

time_tracking/templates/time_tracking/base.html
{% extends "base.html" %}

{% block title %}Time Tracking{%if project %} - {{project}}{%endif%}{% endblock %}

{% block menu %}

{% if project %}
<p>Commands</p>
<ul>
    <li>
        <a href="{{project.get_absolute_url}}">Overview</a>
    </li>
    {% if project.active %}
    <li>
        <a href="{{ project.get_add_record_url }}">Add New Record</a>
    </li>
    {% endif %}
    <li>
        <a href="{{ project.get_edit_url }}">Edit Project</a>
    </li>
    <li>
        <a href="{{ project.get_delete_url }}">Delete Project</a>
    </li>
    <li>
        <a href="{{ project.get_copy_project_url }}">Copy Project</a>
    </li>
</ul>


<p>Categories</p>
<ul>
	{% for category in project.category_set.all %}
	<li><a href="{{category.get_absolute_url}}">{{category}}</a></li>
	{% endfor %}
	<li>
		<a href="{{ project.get_add_category_url }}">Add Category</a>
	</li>
</ul>

<p>Locations</p>
<ul>
    {% for location in locations %}
    <li>
        <a href="{{location.get_absolute_url}}">{{location}}</a>
    </li>
    {% endfor %}
    <li>
        <a href="{{ project.get_add_location_url }}">Add Location</a>
    </li>
</ul>

{% endif %}

{% endblock %}

time_tracking/templates/time_tracking/category_detail.html
{% extends "time_tracking/base.html" %}

{% block content %}

<h1>Category Detail</h1>

<p>Name: {{object.name}}</p>
<p>Slug: {{object.slug}}</p>
<p>
    <a href="{{ object.get_edit_url }}">Edit</a>
    <a href="{{ object.get_delete_url }}">Delete</a>
</p>

<h1>Open Records</h1>

{% for record in open_records %}
    <p>Record: {{ record.start_time }}
        <a href="{{ record.get_delete_url }}">Delete</a>
        <a href="{{ record.get_close_url }}">Close</a>
        <a href="{{ record.get_edit_url }}">Edit</a>
    </p>
{% empty %}
    <p>Empty</p>

{% endfor %}

<h1>Closed Records</h1>

{% for record in closed_records %}
    <p>Record: {{ record.start_time }} -> {{ record.end_time }} {{ record.start_time|timesince:record.end_time}}
        {{ record.duration }}
        <a href="{{ record.get_delete_url }}">Delete</a>
        <a href="{{ record.get_edit_url }}">Edit</a>
    </p>
{% empty %}
    <p>Empty</p>

{% endfor %}


<p><a href="{{ object.project.get_absolute_url }}">Back to Project</a></p>

{% endblock %}

time_tracking/templates/time_tracking/category_form.html
{% extends "time_tracking/base.html" %}

{% block content %}

<h1>{{command}} Category</h1>

{% if form.non_field_errors %}
<div>
    <strong>ERROR:</strong> {{ form.non_field_errors|striptags }}
</div>
{% endif %}

<form action="" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>

{% endblock %}

time_tracking/templates/time_tracking/license.html
{% extends "time_tracking/base.html" %}

{#
time_tracking provides time tracking capabilities to be used in the
django framework.
Copyright (C) 2013 Robert Robinson rerobins@meerkatlabs.org

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
#}

{% block content %}

<p>time_tracking provides time tracking capabilities to be used in the
django framework.</p>
<p>Copyright (C) 2013 Robert Robinson rerobins@meerkatlabs.org</p>

<p>This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.</p>

<p>This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.</p>

<p>You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see
<a href="http://www.gnu.org/licenses/">http://www.gnu.org/licenses/</a>.</p>

{% endblock %}

time_tracking/templates/time_tracking/location_detail.html
{% extends "time_tracking/base.html" %}

{% block content %}

<h1>Location Detail</h1>

<p>Name: {{object.name}}</p>
<p>Slug: {{object.slug}}</p>
<p>
    <a href="{{ object.get_edit_url }}">Edit</a>
    <a href="{{ object.get_delete_url }}">Delete</a>
</p>

<p>Location: {{ object.location }}</p>

<p><a href="{{ object.project.get_absolute_url }}">Back to Project</a></p>

{% endblock %}

time_tracking/templates/time_tracking/location_form.html
{% extends "time_tracking/base.html" %}

{% block content %}

<h1>Edit Location Form</h1>

{% if form.non_field_errors %}
<div>
    <strong>ERROR:</strong> {{ form.non_field_errors|striptags }}
</div>
{% endif %}

<form action="" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>

{% endblock %}

time_tracking/templates/time_tracking/location_list.html
{% extends "time_tracking/base.html" %}

{% block content %}

<p><a href="{% url 'location_create_view' %}">Create Location</a></p>

<h1>Locations</h1>
{% for o in locations %}

    <p><a href="{{ o.get_absolute_url }}">{{o.name}}</a>
        <a href="{{ o.get_edit_url }}">Edit</a>
        <a href="{{ o.get_delete_url }}">Delete</a></p>

{% endfor %}

{% endblock %}

time_tracking/templates/time_tracking/project_confirm_delete.html
{% extends "time_tracking/base.html" %}

{% block content %}

<div>
    <p>
        Are you sure you want to delete?
    </p>

    <form method="post" action=".">
        {% csrf_token %}

        <button type="submit">
            Yes
        </button>
    </form>
</div>

{% endblock %}

time_tracking/templates/time_tracking/project_copy.html
{% extends "time_tracking/base.html" %}

{% block content %}


<h1>{{command}} Project <small>{{project.name}}</small></h1>

<div>

    {% if form.non_field_errors %}
    <div>
        <strong>ERROR:</strong> {{ form.non_field_errors|striptags }}
    </div>
    {% endif %}

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}

        <div>
            <button type="submit">
                {{command}} Project
            </button>
            {% if project %}
            <a href="{{project.get_absolute_url}}">
                Cancel
            </a>
            {% else %}
            <a href="{% url 'project_list_view' %}">
                Cancel
            </a>
            {% endif %}
        </div>
    </form>

</div>


{% endblock %}

time_tracking/templates/time_tracking/project_detail.html
{% extends "time_tracking/base.html" %}

{% load staticfiles %}

{% block title %}Time Tracking - {{project}}{% endblock %}

{% block content %}

<div>

    <h3>Metrics</h3>

    <dl>
        <dt>Total Time Spent:</dt>
        <dd>[[UNKNOWN VALUE]]</dd>

        <dt>Last Recorded Effort:</dt>
        <dd>[[UNKNOWN VALUE]]</dd>
    </dl>

</div>


<div>
    <h3>Open Records</h3>
    {% if open_records %}
    <table>
        <thead>
            <tr>
                <th>Start</th>
                <th>Category</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for record in open_records %}
            {% ifchanged record.start_time.date %}
            <tr>
                <td colspan="3"><strong>{{ record.start_time.date }}</strong></td>
            </tr>
            {% endifchanged %}
            <tr>
                <td>{{record.start_time|time:"TIME_FORMAT" }}</td>
                <td>{{record.category}}</td>
                <td>
                    <div>
                        <p>Action</p>
                        <ul>
                            <li><a href="{{record.get_close_url}}">Close</a></li>
                            <li class="divider"></li>
                            <li><a href="{{record.get_edit_url}}">Edit</a></li>
                            <li><a href="{{record.get_delete_url}}">Delete</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>None</p>
    {% endif %}
</div>


<div class="well well-small">
    <h3>Description</h3>
    <p>{{project.description|default:"None"}}</p>
</div>


<div class="well well-small">
    <h3>Closed Records</h3>
    {% if closed_records %}
    <table>
        <thead>
            <tr>
                <th>Start</th>
                <th>Close</th>
                <th>Category</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for record in closed_records %}
            {% ifchanged record.start_time.date %}
                <tr>
                    <td colspan="4"><strong>{{ record.start_time.date }}</strong></td>
                </tr>
            {% endifchanged %}
            <tr>
                <td>{{record.start_time|time:"TIME_FORMAT" }}</td>
                <td>{{record.end_time|time:"TIME_FORMAT" }}</td>
                <td>{{record.category}}</td>
                <td>
                    <div>
                        <p>Action</p>
                        <ul>
                            <li><a href="{{record.get_edit_url}}">Edit</a></li>
                            <li><a href="{{record.get_delete_url}}">Delete</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>None</p>
    {% endif %}
</div>

{% endblock %}

				

time_tracking/templates/time_tracking/project_form.html
{% extends "time_tracking/base.html" %}

{% block content %}

<h1>{{command}} Project</h1>

{% if form.non_field_errors %}
<div>
    <strong>ERROR:</strong> {{ form.non_field_errors|striptags }}
</div>
{% endif %}

<form action="" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>


{% endblock %}

time_tracking/templates/time_tracking/project_list.html
{% extends "time_tracking/base.html" %}

{% block menu %}
<div>
    <p>Commands</p>
	<ul>
		<li>
			<a href="{% url 'project_create_view' %}">Add Project</a>
		</li>
	</ul>
</div>
{% endblock %}

{% block content %}

<div>
    <h3>Projects</h3>
    {% if active_projects %}
        <dl>
        {% for o in active_projects %}

        <dt>
            <a href="{{ o.get_absolute_url }}">{{o.name}}</a>
        </dt>
        <dd>
            {{o.description|truncatewords_html:10}}
        </dd>

        {% endfor %}
        </dl>
    {% endif %}
</div>

<div>
    <h3>Templates</h3>
    {% if templates %}
        <dl>
        {% for o in templates %}

        <dt>
            <a href="{{ o.get_absolute_url }}">{{o.name}}</a>
        </dt>
        <dd>
            {{o.description|truncatewords_html:10}}
        </dd>

        {% endfor %}
        </dl>
    {% endif %}
</div>

{% endblock %}

time_tracking/templates/time_tracking/record_confirm_delete.html
{% extends "time_tracking/base.html" %}

{% block content %}

<div>
    <p>
        Are you sure you want to delete?
    </p>

    <form method="post" action=".">
        {% csrf_token %}

        <button type="submit">
            Yes
        </button>
    </form>
</div>

{% endblock %}

time_tracking/templates/time_tracking/record_form.html
{% extends "time_tracking/base.html" %}

{% load staticfiles %}

{% block content %}

<h1>{{command}} Record</h1>

{% if form.non_field_errors %}
<div>
    <strong>ERROR:</strong> {{ form.non_field_errors|striptags }}
</div>
{% endif %}

<form action="" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>
{% endblock %}